# -*- coding: utf-8 -*-
"""Generate js/data.js for the offline admissions portal."""
import json
from pathlib import Path

from faculty_catalog import attach_faculty, faculty_payload

# US News Grad CS 2026 approximate ranks (ties collapsed to first mentioned band)
# Combined with Brown CS Open Rankings 2026 US-only ordering for breadth to ~100.
US_SCHOOLS = [
    # (usNewsBand, short, full, state, phdDeadline, phdUrl, msUrl, notes)
    (1, "CMU", "Carnegie Mellon University", "PA", "2026-12-09", "https://www.csd.cs.cmu.edu/academics/doctoral/admissions", "https://csd.cmu.edu/academics/masters/admissions", "SCS opens 2026-09-09; early fee deadline 2026-11-18. PhD full funding. MSCS typically no dept aid."),
    (1, "MIT", "Massachusetts Institute of Technology", "MA", "2026-12-01", "https://oge.mit.edu/programs/electrical-engineering-and-computer-science/", "https://oge.mit.edu/programs/electrical-engineering-and-computer-science/", "EECS PhD fully funded. MEng MIT undergrads only; no terminal SM."),
    (1, "Stanford", "Stanford University", "CA", "2026-12-08", "https://www.cs.stanford.edu/admissions-graduate-application-deadlines", "https://www.cs.stanford.edu/admissions-graduate-application-deadlines", "CS PhD/MS Dec 8 2026. EE PhD Dec 1. KHS Oct 6 2026. MS or PhD exclusive."),
    (1, "UC Berkeley", "University of California, Berkeley", "CA", "2026-12-01", "https://eecs.berkeley.edu/academics/graduate/research-programs/admissions/", "https://grad.berkeley.edu/admissions/our-programs/", "GRE not accepted. MEng Jan 6 2027. MS-only rare."),
    (5, "UIUC", "University of Illinois Urbana-Champaign", "IL", "2026-12-01", "https://siebelschool.illinois.edu/admissions/graduate/application-deadlines", "https://siebelschool.illinois.edu/admissions/graduate/application-deadlines", "PhD/MS Dec 1 CT. MCS Urbana Fall May 1."),
    (5, "Princeton", "Princeton University", "NJ", "2026-12-15", "https://gradschool.princeton.edu/admission-onboarding/prepare/deadlines-and-fees", "https://gradschool.princeton.edu/admission-onboarding/prepare/deadlines-and-fees", "CS & ECE PhD Dec 15. ECE M.Eng Dec 21. Opens Sep 15 2026."),
    (7, "Cornell", "Cornell University", "NY", "2026-12-15", "https://www.cs.cornell.edu/phd-computer-science/apply", "https://www.cs.cornell.edu/", "CS PhD fully funded. IS earlier Dec 1 per LEAP."),
    (7, "Georgia Tech", "Georgia Institute of Technology", "GA", "2026-12-15", "https://www.cc.gatech.edu/phd-cs-admissions-requirements", "https://ece.gatech.edu/future-students/graduate-admissions", "PhD typically GTA/GRA. MS funding limited."),
    (7, "UW", "University of Washington", "WA", "2026-12-15", "https://www.cs.washington.edu/academics/phd", "https://www.cs.washington.edu/academics/ms", "Strong systems/AI. Verify portal when open."),
    (7, "UT Austin", "University of Texas at Austin", "TX", "2026-12-15", "https://www.cs.utexas.edu/graduate/prospective-students", "https://www.cs.utexas.edu/graduate/prospective-students", "CS PhD Dec 15 band (LEAP)."),
    (10, "Caltech", "California Institute of Technology", "CA", "2026-12-15", "https://www.gradoffice.caltech.edu/admissions", "https://www.gradoffice.caltech.edu/admissions", "EE GRE not required. MSEE rarely funded."),
    (12, "Harvard", "Harvard University", "MA", "2026-12-01", "https://www.seas.harvard.edu/computer-science/graduate-program", "https://www.seas.harvard.edu/", "SEAS CS PhD; confirm exact date on Grad School."),
    (12, "UCSD", "University of California, San Diego", "CA", "2026-12-15", "https://cse.ucsd.edu/graduate/admissions", "https://cse.ucsd.edu/graduate/admissions", "CSE PhD typically Dec; MS separate."),
    (12, "UMich", "University of Michigan, Ann Arbor", "MI", "2026-12-15", "https://cse.engin.umich.edu/academics/graduate/admissions/", "https://cse.engin.umich.edu/academics/graduate/", "CSE & ECE both strong. PhD funded."),
    (15, "UCLA", "University of California, Los Angeles", "CA", "2026-12-15", "https://www.cs.ucla.edu/graduate-admissions/", "https://www.cs.ucla.edu/graduate-admissions/", "CS PhD Dec 15 (LEAP)."),
    (16, "Columbia", "Columbia University", "NY", "2026-12-15", "https://www.cs.columbia.edu/education/admissions/", "https://www.cs.columbia.edu/education/ms/", "PhD funded; MS mostly self-pay."),
    (16, "JHU", "Johns Hopkins University", "MD", "2026-12-15", "https://www.cs.jhu.edu/academic-programs/graduate-studies/graduate-admissions/", "https://www.cs.jhu.edu/", "CS + ECE options."),
    (16, "Purdue", "Purdue University", "IN", "2026-12-01", "https://www.cs.purdue.edu/graduate/index.html", "https://engineering.purdue.edu/ECE", "CS PhD Dec 1 (LEAP). Strong ECE."),
    (16, "UMD", "University of Maryland, College Park", "MD", "2026-12-04", "https://www.cs.umd.edu/grad/admissions", "https://www.cs.umd.edu/grad", "CS PhD Dec 4 (LEAP)."),
    (16, "UPenn", "University of Pennsylvania", "PA", "2026-12-15", "https://www.cis.upenn.edu/graduate/admissions/", "https://www.cis.upenn.edu/graduate/", "CIS PhD Dec 15."),
    (16, "USC", "University of Southern California", "CA", "2026-12-15", "https://www.cs.usc.edu/academic-programs/phd/", "https://www.cs.usc.edu/academic-programs/masters/", "PhD funded; large MS population self-pay."),
    (16, "UW–Madison", "University of Wisconsin–Madison", "WI", "2026-12-15", "https://www.cs.wisc.edu/grad/programs/admissions/", "https://www.cs.wisc.edu/grad/programs/admissions/", "MS/PhD Dec 15; PMP/MSDE Feb 15."),
    (16, "Yale", "Yale University", "CT", "2026-12-15", "https://cpsc.yale.edu/academics/graduate-program", "https://cpsc.yale.edu/", "CS PhD Dec 15."),
    (24, "Duke", "Duke University", "NC", "2026-12-14", "https://www.cs.duke.edu/graduate/phd", "https://www.cs.duke.edu/graduate", "Confirm portal; typically mid-Dec."),
    (25, "Brown", "Brown University", "RI", "2026-12-15", "https://cs.brown.edu/degrees/doctoral/", "https://cs.brown.edu/degrees/masters/", "PhD funded."),
    (25, "UChicago", "University of Chicago", "IL", "2026-12-15", "https://cs.uchicago.edu/academics/graduate/", "https://cs.uchicago.edu/", "Growing CS department."),
    (25, "UCI", "University of California, Irvine", "CA", "2026-12-15", "https://www.cs.uci.edu/graduate/", "https://www.cs.uci.edu/graduate/", "ICS graduate programs."),
    (25, "Virginia Tech", "Virginia Tech", "VA", "2026-12-15", "https://cs.vt.edu/Graduate.html", "https://ece.vt.edu/", "CS + ECE."),
    (30, "NYU", "New York University", "NY", "2026-12-12", "https://cs.nyu.edu/home/phd/", "https://cs.nyu.edu/home/master/", "Courant CS; Tandon separate."),
    (30, "Northwestern", "Northwestern University", "IL", "2026-12-01", "https://www.mccormick.northwestern.edu/computer-science/graduate/", "https://www.mccormick.northwestern.edu/computer-science/", "Confirm exact date."),
    (30, "Rice", "Rice University", "TX", "2026-12-15", "https://csweb.rice.edu/academics/graduate-program", "https://csweb.rice.edu/", "PhD funded."),
    (30, "CU Boulder", "University of Colorado Boulder", "CO", "2026-12-15", "https://www.colorado.edu/cs/graduate-programs", "https://www.colorado.edu/cs/", "Dec 15 (LEAP)."),
    (30, "UNC", "University of North Carolina at Chapel Hill", "NC", "2027-03-09", "https://cs.unc.edu/graduate/admissions/", "https://cs.unc.edu/graduate/", "Later deadline Mar 9 2027 (LEAP)—verify."),
    (35, "Northeastern", "Northeastern University", "MA", "2026-12-15", "https://www.khoury.northeastern.edu/programs/phd-in-computer-science/", "https://www.khoury.northeastern.edu/", "Large co-op MS programs."),
    (35, "UC Davis", "University of California, Davis", "CA", "2026-12-15", "https://cs.ucdavis.edu/graduate", "https://cs.ucdavis.edu/graduate", "Dec 15 (LEAP)."),
    (35, "UCSB", "University of California, Santa Barbara", "CA", "2026-12-15", "https://www.cs.ucsb.edu/education/graduate/admissions", "https://www.cs.ucsb.edu/", "Strong systems/security."),
    (35, "UMass", "University of Massachusetts Amherst", "MA", "2026-12-15", "https://www.cics.umass.edu/admissions/graduate-admissions", "https://www.cics.umass.edu/", "CICS; strong NLP/IR historically."),
    (39, "Dartmouth", "Dartmouth College", "NH", "2026-12-15", "https://web.cs.dartmouth.edu/graduate/", "https://web.cs.dartmouth.edu/", "Smaller cohort."),
    (39, "Ohio State", "Ohio State University", "OH", "2026-12-01", "https://cse.osu.edu/graduate", "https://ece.osu.edu/", "Confirm exact CS deadline."),
    (39, "Penn State", "Pennsylvania State University", "PA", "2026-12-15", "https://www.eecs.psu.edu/students/graduate/Graduate-Apply.aspx", "https://www.eecs.psu.edu/", "EECS."),
    (39, "UMN", "University of Minnesota Twin Cities", "MN", "2026-12-01", "https://cse.umn.edu/cs/graduate", "https://cse.umn.edu/ece", "CS + ECE."),
    (39, "UVA", "University of Virginia", "VA", "2026-12-15", "https://engineering.virginia.edu/departments/computer-science/academics/cs-graduate-programs", "https://engineering.virginia.edu/", "CS PhD."),
    (39, "Vanderbilt", "Vanderbilt University", "TN", "2026-12-15", "https://engineering.vanderbilt.edu/cs/", "https://engineering.vanderbilt.edu/", "CS/ECE."),
    (45, "ASU", "Arizona State University", "AZ", "2026-12-15", "https://degree.engineering.asu.edu/computer-science/", "https://degree.engineering.asu.edu/", "Large online MCS options."),
    (45, "Texas A&M", "Texas A&M University", "TX", "2026-12-15", "https://engineering.tamu.edu/cse/academics/graduate/index.html", "https://engineering.tamu.edu/ece/", "Dec 15 (LEAP)."),
    (45, "Rutgers", "Rutgers University–New Brunswick", "NJ", "2026-12-15", "https://www.cs.rutgers.edu/academics/graduate", "https://www.ece.rutgers.edu/", "CS + ECE."),
    (45, "Stony Brook", "Stony Brook University (SUNY)", "NY", "2026-12-15", "https://www.cs.stonybrook.edu/students/Graduate-Programs", "https://www.cs.stonybrook.edu/", "Strong systems/theory value."),
    (48, "UUtah", "University of Utah", "UT", "2026-12-15", "https://www.cs.utah.edu/graduate/", "https://www.cs.utah.edu/", "Graphics historically strong."),
    (48, "WashU", "Washington University in St. Louis", "MO", "2026-12-15", "https://cse.wustl.edu/graduate/index.html", "https://cse.wustl.edu/", "CSE PhD."),
    (50, "NCSU", "North Carolina State University", "NC", "2026-12-15", "https://www.csc.ncsu.edu/academics/graduate/", "https://ece.ncsu.edu/", "CSC + ECE."),
    (50, "Notre Dame", "University of Notre Dame", "IN", "2026-12-15", "https://cse.nd.edu/graduate/", "https://cse.nd.edu/", "CSE."),
    (50, "Rochester", "University of Rochester", "NY", "2026-12-15", "https://www.cs.rochester.edu/graduate/", "https://www.hajim.rochester.edu/ece/", "CS + ECE."),
    (55, "UFlorida", "University of Florida", "FL", "2026-12-05", "https://www.cise.ufl.edu/academics/grad/", "https://www.ece.ufl.edu/", "Confirm CISE deadline."),
    (55, "BU", "Boston University", "MA", "2026-12-15", "https://www.bu.edu/cs/phd-program/", "https://www.bu.edu/cs/", "CS PhD."),
    (55, "IU", "Indiana University Bloomington", "IN", "2026-12-01", "https://cs.indiana.edu/graduate/", "https://cs.indiana.edu/", "Luddy School."),
    (55, "Iowa State", "Iowa State University", "IA", "2026-12-15", "https://www.cs.iastate.edu/graduate-programs", "https://www.ece.iastate.edu/", "CS + ECE."),
    (58, "Oregon State", "Oregon State University", "OR", "2026-12-15", "https://eecs.oregonstate.edu/graduate-programs", "https://eecs.oregonstate.edu/", "EECS."),
    (60, "UCSC", "University of California, Santa Cruz", "CA", "2027-01-05", "https://engineering.ucsc.edu/departments/computer-science-and-engineering/", "https://engineering.ucsc.edu/", "Jan 5 2027 (LEAP)."),
    (60, "UCR", "University of California, Riverside", "CA", "2026-12-15", "https://www1.cs.ucr.edu/graduate", "https://www1.cs.ucr.edu/", "CSE."),
    (62, "UIC", "University of Illinois Chicago", "IL", "2026-12-15", "https://cs.uic.edu/graduate/", "https://cs.uic.edu/", "Not to confuse with HK UIC/BNBU."),
    (62, "UCF", "University of Central Florida", "FL", "2026-12-15", "https://www.cs.ucf.edu/graduate/", "https://www.cs.ucf.edu/", "CS."),
    (62, "Buffalo", "University at Buffalo (SUNY)", "NY", "2026-12-15", "https://engineering.buffalo.edu/computer-science-engineering.html", "https://engineering.buffalo.edu/", "CSE."),
    (65, "MSU", "Michigan State University", "MI", "2026-12-15", "https://www.cse.msu.edu/Students/Graduate/", "https://www.egr.msu.edu/ece/", "CSE + ECE."),
    (65, "Pitt", "University of Pittsburgh", "PA", "2026-12-15", "https://www.cs.pitt.edu/graduate", "https://www.engineering.pitt.edu/ECE/", "CS."),
    (65, "UArizona", "University of Arizona", "AZ", "2026-12-15", "https://www.cs.arizona.edu/graduate", "https://ece.arizona.edu/", "CS + ECE."),
    (70, "GMU", "George Mason University", "VA", "2026-12-15", "https://cs.gmu.edu/prospective-students/graduate/", "https://ece.gmu.edu/", "CS."),
    (70, "UT Dallas", "University of Texas at Dallas", "TX", "2026-12-15", "https://cs.utdallas.edu/academics/graduate-programs/", "https://ece.utdallas.edu/", "CS + ECE."),
    (70, "Tufts", "Tufts University", "MA", "2026-12-15", "https://engineering.tufts.edu/cs/graduate-programs", "https://engineering.tufts.edu/", "CS."),
    (75, "RPI", "Rensselaer Polytechnic Institute", "NY", "2026-12-15", "https://science.rpi.edu/computer-science/programs/grad", "https://www.ecse.rpi.edu/", "CS + ECSE."),
    (75, "Case Western", "Case Western Reserve University", "OH", "2026-12-15", "https://engineering.case.edu/computer-and-data-sciences", "https://engineering.case.edu/", "CDS."),
    (75, "UMBC", "University of Maryland, Baltimore County", "MD", "2027-01-20", "https://www.csee.umbc.edu/graduate/", "https://www.csee.umbc.edu/", "Jan 20 2027 (LEAP)."),
    (78, "Stevens", "Stevens Institute of Technology", "NJ", "2026-12-15", "https://www.stevens.edu/school-of-engineering-and-science/departments/computer-science", "https://www.stevens.edu/", "CS."),
    (78, "UDelaware", "University of Delaware", "DE", "2026-12-15", "https://www.cis.udel.edu/graduate/", "https://www.ece.udel.edu/", "CIS."),
    (78, "UNebraska", "University of Nebraska–Lincoln", "NE", "2026-12-15", "https://computing.unl.edu/", "https://engineering.unl.edu/ece/", "Computing."),
    (80, "FSU", "Florida State University", "FL", "2026-12-15", "https://www.cs.fsu.edu/graduate/", "https://www.eng.famu.fsu.edu/ece", "CS."),
    (80, "Syracuse", "Syracuse University", "NY", "2026-12-15", "https://ecs.syracuse.edu/academics/computer-science", "https://ecs.syracuse.edu/", "Dec 15 (LEAP)."),
    (80, "WSU", "Washington State University", "WA", "2026-12-15", "https://school.eecs.wsu.edu/", "https://school.eecs.wsu.edu/", "EECS."),
    (85, "Clemson", "Clemson University", "SC", "2026-12-15", "https://www.clemson.edu/cecas/departments/computing/", "https://www.clemson.edu/cecas/departments/ece/", "Computing."),
    (85, "Drexel", "Drexel University", "PA", "2026-12-15", "https://drexel.edu/cci/academics/doctoral-programs/", "https://drexel.edu/cci/", "CCI."),
    (85, "UConn", "University of Connecticut", "CT", "2026-12-15", "https://www.cse.uconn.edu/graduate/", "https://www.ee.uconn.edu/", "CSE."),
    (85, "TTIC", "Toyota Technological Institute at Chicago", "IL", "2026-12-15", "https://www.ttic.edu/admissions/", "https://www.ttic.edu/", "PhD-focused CS institute."),
    (90, "UNC Charlotte", "University of North Carolina at Charlotte", "NC", "2026-12-15", "https://cci.charlotte.edu/", "https://cci.charlotte.edu/", "CCI."),
    (90, "UT Arlington", "University of Texas at Arlington", "TX", "2026-12-15", "https://www.uta.edu/academics/schools-colleges/engineering/academics/departments/cse", "https://www.uta.edu/academics/schools-colleges/engineering/academics/departments/ee", "CSE."),
    (90, "UIowa", "University of Iowa", "IA", "2026-12-15", "https://cs.uiowa.edu/graduate-program", "https://engineering.uiowa.edu/ece", "CS."),
    (92, "Georgetown", "Georgetown University", "DC", "2026-12-15", "https://cs.georgetown.edu/graduate/", "https://cs.georgetown.edu/", "CS."),
    (92, "GWU", "George Washington University", "DC", "2026-12-15", "https://www.cs.seas.gwu.edu/", "https://www.ece.seas.gwu.edu/", "CS + ECE."),
    (92, "Binghamton", "Binghamton University (SUNY)", "NY", "2026-12-15", "https://www.binghamton.edu/computer-science/", "https://www.binghamton.edu/watson/ece/", "CS."),
    (95, "NJIT", "New Jersey Institute of Technology", "NJ", "2026-12-15", "https://computing.njit.edu/", "https://ece.njit.edu/", "Computing."),
    (95, "WPI", "Worcester Polytechnic Institute", "MA", "2026-12-15", "https://www.wpi.edu/academics/departments/computer-science", "https://www.wpi.edu/academics/departments/electrical-computer-engineering", "CS + ECE."),
    (95, "UTK", "University of Tennessee, Knoxville", "TN", "2026-12-15", "https://www.eecs.utk.edu/", "https://www.eecs.utk.edu/", "EECS."),
    (98, "Emory", "Emory University", "GA", "2026-12-15", "https://www.cs.emory.edu/graduate/", "https://www.cs.emory.edu/", "CS."),
    (98, "UGA", "University of Georgia", "GA", "2026-12-15", "https://www.cs.uga.edu/graduate", "https://www.ece.uga.edu/", "CS."),
    (98, "Temple", "Temple University", "PA", "2026-12-15", "https://cis.temple.edu/graduate", "https://engineering.temple.edu/academics/departments/electrical-computer-engineering", "CIS."),
    (100, "Lehigh", "Lehigh University", "PA", "2026-12-15", "https://engineering.lehigh.edu/cse", "https://engineering.lehigh.edu/ece", "CSE."),
    (100, "IIT", "Illinois Institute of Technology", "IL", "2026-12-15", "https://www.iit.edu/computer-science", "https://www.iit.edu/ece", "CS."),
    (100, "Auburn", "Auburn University", "AL", "2026-12-15", "https://www.eng.auburn.edu/comp/", "https://www.eng.auburn.edu/ece/", "CS + ECE."),
    (100, "UH", "University of Houston", "TX", "2026-12-15", "https://www.cs.uh.edu/graduate/", "https://www.ece.uh.edu/", "CS."),
    (100, "Colorado Mines", "Colorado School of Mines", "CO", "2026-12-15", "https://cs.mines.edu/", "https://ece.mines.edu/", "CS + EE."),
]

def us_programs():
    programs = []
    for band, short, full, state, phd_dl, phd_url, ms_url, notes in US_SCHOOLS:
        programs.append({
            "id": f"us-{short.lower().replace(' ', '-').replace('–', '-')}-phd",
            "region": "US",
            "campusType": "main",
            "school": short,
            "schoolFull": full,
            "state": state,
            "rankBand": band,
            "rankSource": "US News Grad CS 2026 band (approx) + Brown Open Rankings breadth",
            "field": "CS/EE",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "Fall 2027",
            "deadline": phd_dl,
            "deadlineNote": "Confirm on official portal when application opens",
            "opens": "Usually mid–late Sep 2026",
            "funding": "full",
            "fundingDetail": "US research PhD admits typically receive stipend + tuition waiver via RA/TA/fellowship while in good standing.",
            "gre": "Often optional or not accepted — check portal",
            "english": "TOEFL/IELTS (or school-specific) for most international applicants",
            "requirements": [
                "Bachelor's degree (Master's usually not required)",
                "Statement of Purpose / research statement",
                "Usually 3 letters of recommendation",
                "Transcripts + CV/resume",
            ],
            "materials": ["Online grad app", "SoP", "LoR×3", "Transcripts", "CV", "English scores if required"],
            "notes": notes,
            "applyUrl": phd_url,
            "infoUrl": phd_url,
            "detailLevel": "verified-deadline" if "LEAP" in notes or any(x in notes for x in ["2026-12", "SCS", "EECS", "Dec 8", "Dec 1", "Dec 15", "KHS"]) else "portal-check",
        })
        programs.append({
            "id": f"us-{short.lower().replace(' ', '-').replace('–', '-')}-ms",
            "region": "US",
            "campusType": "main",
            "school": short,
            "schoolFull": full,
            "state": state,
            "rankBand": band,
            "rankSource": "US News Grad CS 2026 band (approx) + Brown Open Rankings breadth",
            "field": "CS/EE",
            "degree": "MS/MEng/MCS",
            "degreeGroup": "Master",
            "entry": "Fall 2027 (some also Spring)",
            "deadline": "Varies — often Dec–Jan for research MS; professional MCS later",
            "deadlineNote": "Many professional MS deadlines are later than PhD; some schools have separate MCS portals.",
            "opens": "Usually Fall 2026",
            "funding": "self",
            "fundingDetail": "Most taught/professional MS are self-funded. Research MS funding is uncommon and competitive. Do not assume PhD-level aid.",
            "gre": "Program-dependent",
            "english": "TOEFL/IELTS for most international applicants",
            "requirements": [
                "Bachelor's in CS/EE/related (or bridge coursework)",
                "SoP, LoR (often 2–3), transcripts",
            ],
            "materials": ["Online app", "SoP", "LoR", "Transcripts", "CV"],
            "notes": notes + " MS funding rare vs PhD.",
            "applyUrl": ms_url,
            "infoUrl": ms_url,
            "detailLevel": "portal-check",
        })
    return programs


def hk_programs():
    return [
        # ——— Hong Kong main campuses ———
        {
            "id": "hk-hku-cs-phd",
            "region": "HK",
            "campusType": "main",
            "school": "HKU",
            "schoolFull": "The University of Hong Kong",
            "location": "Pokfulam, Hong Kong",
            "field": "CS",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "Sep 2027",
            "deadline": "2026-12-01",
            "deadlineNote": "Main round; clearing 2027-04-30 / 2027-08-31",
            "opens": "2026-09-01",
            "funding": "full",
            "fundingDetail": "PGS ≥ HK$225,120/yr; Presidential PhD ~HK$433k yr1; HKPFS HK$344,400/yr + travel HK$14,400",
            "gre": "Usually not required",
            "english": "TOEFL iBT ≥85 if prior degree not English-taught",
            "requirements": ["Honours Bachelor+", "Research Proposal", "Indicate HKPF for Dec 1 round"],
            "materials": ["GS online app", "Research Proposal", "Transcripts", "References"],
            "notes": "Early recruitment rounds Apr/Aug 2026. HKPFS must use main round.",
            "applyUrl": "https://gradsch.hku.hk/prospective_students/application/how_to_apply",
            "infoUrl": "https://www.cs.hku.hk/programmes/research-based/how-to-apply-2027",
            "detailLevel": "verified",
        },
        {
            "id": "hk-hku-cs-mphil",
            "region": "HK",
            "campusType": "main",
            "school": "HKU",
            "schoolFull": "The University of Hong Kong",
            "location": "Pokfulam, Hong Kong",
            "field": "CS",
            "degree": "MPhil",
            "degreeGroup": "Master",
            "entry": "Sep 2027",
            "deadline": "2026-12-01",
            "deadlineNote": "Research MPhil (not taught MSc)",
            "opens": "2026-09-01",
            "funding": "full",
            "fundingDetail": "Full-time RPG typically receives PGS. HKPFS is PhD-only.",
            "gre": "Usually not required",
            "english": "TOEFL iBT ≥85 if needed",
            "requirements": ["Bachelor with honours", "Research Proposal"],
            "materials": ["GS online app", "Research Proposal", "Transcripts", "References"],
            "notes": "Same timeline as PhD research degrees.",
            "applyUrl": "https://gradsch.hku.hk/prospective_students/application/how_to_apply",
            "infoUrl": "https://www.cs.hku.hk/programmes/research-based/mphil-phd-admission",
            "detailLevel": "verified",
        },
        {
            "id": "hk-cuhk-cse-phd",
            "region": "HK",
            "campusType": "main",
            "school": "CUHK",
            "schoolFull": "The Chinese University of Hong Kong",
            "location": "Sha Tin, Hong Kong",
            "field": "CSE",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "2027-28",
            "deadline": "2026-10-06",
            "deadlineNote": "R1 HKPFS last; R2 2027-01-12; R3 2027-03-31",
            "opens": "2026-09-01",
            "funding": "full",
            "fundingDetail": "~HK$19,100/mo stipend; HKPFS ~HK$28,400/mo + travel ~HK$14,200/yr",
            "gre": "Not required",
            "english": "University English requirements",
            "requirements": ["CV + transcript + class ranking to CSE PG system", "Interview if shortlisted"],
            "materials": ["CUHK GS + CSE upload", "References", "Interview"],
            "notes": "CSE R1 ends Oct 6 — earlier than RGC Dec 1.",
            "applyUrl": "https://www.cse.cuhk.edu.hk/admission/mphil-phd/regular-admission/",
            "infoUrl": "https://www.cse.cuhk.edu.hk/admission/mphil-phd/regular-admission/",
            "detailLevel": "verified",
        },
        {
            "id": "hk-cuhk-cse-mphil",
            "region": "HK",
            "campusType": "main",
            "school": "CUHK",
            "schoolFull": "The Chinese University of Hong Kong",
            "location": "Sha Tin, Hong Kong",
            "field": "CSE",
            "degree": "MPhil",
            "degreeGroup": "Master",
            "entry": "2027-28",
            "deadline": "2026-10-06",
            "deadlineNote": "Same 3 rounds as PhD",
            "opens": "2026-09-01",
            "funding": "full",
            "fundingDetail": "~HK$19,100/mo for full-time research students",
            "gre": "Not required",
            "english": "University English requirements",
            "requirements": ["Academic + research potential", "CSE document upload"],
            "materials": ["CUHK GS + CSE docs"],
            "notes": "HKPFS PhD-only.",
            "applyUrl": "https://www.cse.cuhk.edu.hk/admission/mphil-phd/regular-admission/",
            "infoUrl": "https://www.cse.cuhk.edu.hk/admission/mphil-phd/regular-admission/",
            "detailLevel": "verified",
        },
        {
            "id": "hk-cuhk-ie-phd",
            "region": "HK",
            "campusType": "main",
            "school": "CUHK",
            "schoolFull": "The Chinese University of Hong Kong",
            "location": "Sha Tin, Hong Kong",
            "field": "IE/EE",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "2027-28",
            "deadline": "2026-12-01",
            "deadlineNote": "Clearing 2027-03-31",
            "opens": "2026-09-01",
            "funding": "full",
            "fundingDetail": "PGS + HKPFS track; tuition HK$49,500 (2027/28)",
            "gre": "Usually not required",
            "english": "GS English requirements",
            "requirements": ["2-page SoP/RS", "CV with pubs", "Related engineering/science background"],
            "materials": ["CUHK online app", "SoP", "CV", "LoR"],
            "notes": "HKPFS: RGC noon + CUHK 23:59 on Dec 1.",
            "applyUrl": "https://www.gs.cuhk.edu.hk/admissions/application/online-application",
            "infoUrl": "https://www.gs.cuhk.edu.hk/programmes/engineering/mphil-phd-information-engineering",
            "detailLevel": "verified",
        },
        {
            "id": "hk-cuhk-ele-phd",
            "region": "HK",
            "campusType": "main",
            "school": "CUHK",
            "schoolFull": "The Chinese University of Hong Kong",
            "location": "Sha Tin, Hong Kong",
            "field": "EE",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "2027-28",
            "deadline": "2026-12-01",
            "deadlineNote": "Clearing 2027-03-31",
            "opens": "2026-09-01",
            "funding": "full",
            "fundingDetail": "Regular PGS; HKPFS for nominees",
            "gre": "Usually not required",
            "english": "GS English requirements",
            "requirements": ["EE/CompE/Physics-electronics related preferred"],
            "materials": ["CUHK online app"],
            "notes": "Same HKPFS dual deadline.",
            "applyUrl": "https://www.gs.cuhk.edu.hk/admissions/application/online-application",
            "infoUrl": "https://www.gs.cuhk.edu.hk/programmes/engineering/mphil-phd-electronic-engineering",
            "detailLevel": "verified",
        },
        {
            "id": "hk-hkust-cse-phd",
            "region": "HK",
            "campusType": "main",
            "school": "HKUST",
            "schoolFull": "Hong Kong University of Science and Technology",
            "location": "Clear Water Bay, Hong Kong",
            "field": "CSE",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "Fall 2027",
            "deadline": "2026-12-01",
            "deadlineNote": "HKPFS RGC noon / HKUST 23:59; early recruiting was 2026-08-15",
            "opens": "2026-09-01",
            "funding": "full",
            "fundingDetail": "~HK$229,620/yr; HKPFS ~HK$28,400/mo + travel + HKUST HK$40,000 one-time",
            "gre": "Not required",
            "english": "TOEFL iBT 80/4.5 or IELTS 6.5 (sub≥5.5); no home tests",
            "requirements": ["Bachelor by enrollment", "Strong record for HKPF"],
            "materials": ["FYTGS OAS", "HKPFS ref # if any"],
            "notes": "Tuition ~HK$49,500. Rolling offers.",
            "applyUrl": "https://fytgs.hkust.edu.hk/apply",
            "infoUrl": "https://cse.hkust.edu.hk/pg/admissions/recruiting/",
            "detailLevel": "verified",
        },
        {
            "id": "hk-hkust-cse-mphil",
            "region": "HK",
            "campusType": "main",
            "school": "HKUST",
            "schoolFull": "Hong Kong University of Science and Technology",
            "location": "Clear Water Bay, Hong Kong",
            "field": "CSE",
            "degree": "MPhil",
            "degreeGroup": "Master",
            "entry": "Fall 2027 (~2 yrs)",
            "deadline": "Program-specific after Dec 2026",
            "deadlineNote": "Apply early; rolling",
            "opens": "2026-09-01",
            "funding": "full",
            "fundingDetail": "~HK$229,620/yr RPG scholarship",
            "gre": "Not required",
            "english": "Same as PhD minima",
            "requirements": ["Bachelor from recognized institution"],
            "materials": ["FYTGS OAS"],
            "notes": "Check FYTGS program closing dates.",
            "applyUrl": "https://fytgs.hkust.edu.hk/apply",
            "infoUrl": "https://prog-crs.hkust.edu.hk/pgprog/2026-27/mphil-phd-cse",
            "detailLevel": "verified",
        },
        {
            "id": "hk-cityu-ee-phd",
            "region": "HK",
            "campusType": "main",
            "school": "CityUHK",
            "schoolFull": "City University of Hong Kong",
            "location": "Kowloon Tong, Hong Kong",
            "field": "EE",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "2027/28",
            "deadline": "2026-12-01",
            "deadlineNote": "RGC 12:00; CityU 23:59",
            "opens": "2026-09-01",
            "funding": "full",
            "fundingDetail": "HKPFS HK$344,400/yr + travel; CityU continues year-4 stipend; else regular studentship",
            "gre": "Not required by scheme",
            "english": "TOEFL 79 / IELTS 6.5 typical RPG minima",
            "requirements": ["Contact supervisor + research proposal for HKPFS", "RGC + CityU dual apply"],
            "materials": ["RGC OAS", "CityU OAS", "Proposal", "Referees"],
            "notes": "Regular RPG year-round; HKPFS hard Dec 1.",
            "applyUrl": "https://www.cityu.edu.hk/pg/research-degree-programmes/steps-and-procedures",
            "infoUrl": "https://www.ee.cityu.edu.hk/current_students/research_degree/application",
            "detailLevel": "verified",
        },
        {
            "id": "hk-polyu-eee-phd",
            "region": "HK",
            "campusType": "main",
            "school": "PolyU",
            "schoolFull": "The Hong Kong Polytechnic University",
            "location": "Hung Hom, Hong Kong",
            "field": "EEE",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "Sep 2027",
            "deadline": "2026-12-01",
            "deadlineNote": "HKPFS 2026-12-01; regular PhD/MPhil 2027-05-31",
            "opens": "Open for 2027 entry",
            "funding": "full",
            "fundingDetail": "RPG studentship; HKPFS for nominees",
            "gre": "Check department",
            "english": "PolyU English requirements",
            "requirements": ["2 academic referee reports (HKPFS before deadline)"],
            "materials": ["PolyU RPG app", "Referees", "Transcripts"],
            "notes": "Do not wait until May if seeking HKPFS.",
            "applyUrl": "https://www.polyu.edu.hk/study/pg/rpg/2027/eee",
            "infoUrl": "https://www.polyu.edu.hk/gs/hkpfs/",
            "detailLevel": "verified",
        },
        {
            "id": "hk-polyu-comp-phd",
            "region": "HK",
            "campusType": "main",
            "school": "PolyU",
            "schoolFull": "The Hong Kong Polytechnic University",
            "location": "Hung Hom, Hong Kong",
            "field": "Computing",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "May/Sep 2027 tracks",
            "deadline": "2026-12-01",
            "deadlineNote": "HKPFS Dec 1; regular often Jan 2027 — check Computing page",
            "opens": "Rolling toward deadlines",
            "funding": "full",
            "fundingDetail": "RPG studentship + HKPFS",
            "gre": "Check department",
            "english": "PolyU English requirements",
            "requirements": ["Bachelor/Master in computing-related fields"],
            "materials": ["PolyU RPG app"],
            "notes": "Faculty of Computer and Mathematical Sciences offers Computing / DSAI RPG.",
            "applyUrl": "https://www.polyu.edu.hk/study/pg/research-postgraduate",
            "infoUrl": "https://www.polyu.edu.hk/study/pg/research-postgraduate",
            "detailLevel": "portal-check",
        },
        {
            "id": "hk-hkbu-cs-phd",
            "region": "HK",
            "campusType": "main",
            "school": "HKBU",
            "schoolFull": "Hong Kong Baptist University",
            "location": "Kowloon Tong, Hong Kong",
            "field": "CS",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "2027/28",
            "deadline": "2026-12-01",
            "deadlineNote": "HKPFS full app 23:59",
            "opens": "2026-09-01",
            "funding": "full",
            "fundingDetail": "PGS + HKPFS eligibility",
            "gre": "Usually not required",
            "english": "HKBU English requirements",
            "requirements": ["Follow GS + department"],
            "materials": ["HKBU GS app", "HKPFS ref #"],
            "notes": "HKPFS participating university.",
            "applyUrl": "https://gs.hkbu.edu.hk/",
            "infoUrl": "https://cerg1.ugc.edu.hk/hkpfs/institutions.html",
            "detailLevel": "portal-check",
        },
        # ——— Mainland campuses of HK institutions ———
        {
            "id": "hk-hkustgz-phd",
            "region": "HK",
            "campusType": "mainland",
            "school": "HKUST(GZ)",
            "schoolFull": "HKUST (Guangzhou)",
            "location": "Nansha, Guangzhou, Mainland China",
            "field": "Hubs/Thrusts (CS/AI/EE related)",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "Fall 2027 (also Spring 2027 PhD)",
            "deadline": "2027-06-15",
            "deadlineNote": "Intl Fall PhD to 2027-06-15; Chinese applicants to 2027-07-15. Spring PhD intl to 2026-12-04",
            "opens": "2026-07-21",
            "funding": "full",
            "fundingDetail": "GZ campus scholarships/stipends (see FYTGS GZ). Not the same as HKPFS (HKPFS is HK campuses).",
            "gre": "Not typically required",
            "english": "University English requirements",
            "requirements": ["Bachelor/Master per PhD rules", "Rolling offers"],
            "materials": ["FYTGS (GZ) OAS"],
            "notes": "Cross-disciplinary hubs. Separate from Clear Water Bay HKUST.",
            "applyUrl": "https://fytgs.hkust-gz.edu.cn/admissions/before-submitting-an-application/admission-timeline",
            "infoUrl": "https://fytgs.hkust-gz.edu.cn/",
            "detailLevel": "verified",
        },
        {
            "id": "hk-hkustgz-rbm",
            "region": "HK",
            "campusType": "mainland",
            "school": "HKUST(GZ)",
            "schoolFull": "HKUST (Guangzhou) — Red Bird MPhil",
            "location": "Nansha, Guangzhou, Mainland China",
            "field": "Interdisciplinary MPhil",
            "degree": "MPhil (Red Bird)",
            "degreeGroup": "Master",
            "entry": "Fall 2027",
            "deadline": "2027-03-01",
            "deadlineNote": "23:59; late apps roll to 2028 Fall",
            "opens": "2026-04-02",
            "funding": "partial",
            "fundingDetail": "See CFT scholarships & fees pages; different from standard RPG PGS.",
            "gre": "Not required",
            "english": "Must meet English language requirements",
            "requirements": [
                "Bachelor degree; no major restriction",
                "Offline interview important",
                "Select MPhil (General) in OAS",
            ],
            "materials": ["OAS application", "PS/proposal encouraged but not mandatory"],
            "notes": "Project-based interdisciplinary MPhil. Contact rbmadmit@hkust-gz.edu.cn",
            "applyUrl": "https://cft.hkust-gz.edu.cn/admission/",
            "infoUrl": "https://cft.hkust-gz.edu.cn/admission/",
            "detailLevel": "verified",
        },
        {
            "id": "hk-cuhksz-cie-phd",
            "region": "HK",
            "campusType": "mainland",
            "school": "CUHK-Shenzhen",
            "schoolFull": "The Chinese University of Hong Kong, Shenzhen",
            "location": "Longgang, Shenzhen, Mainland China",
            "field": "CIE (CS/Info Eng)",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "Fall 2027 / Spring 2027",
            "deadline": "2027-05-31",
            "deadlineNote": "Fall 2027-28: 2026-09-01 to 2027-05-31; Spring 2026-27: to 2026-10-15",
            "opens": "2026-09-01 (Fall)",
            "funding": "full",
            "fundingDetail": "From 2027 tuition RMB162,000/yr. Presidential Fellowship RMB180,000/yr stipend + tuition subsidy; Dean’s full tuition waiver; school studentships",
            "gre": "Not required",
            "english": "TOEFL 79/4.5 or IELTS 6.5 (or exemptions)",
            "requirements": ["Master or strong Bachelor", "Contact supervisor recommended", "Interview possible"],
            "materials": ["https://pgapply.cuhk.edu.cn/", "2 confidential refs", "Transcripts", "CV+PS", "RMB600 fee"],
            "notes": "Degree awarded by CUHK. Not HKPFS (mainland campus).",
            "applyUrl": "https://pgapply.cuhk.edu.cn/",
            "infoUrl": "https://sse-mphil-phd.cuhk.edu.cn/en/program/CIE",
            "detailLevel": "verified",
        },
        {
            "id": "hk-cuhksz-cie-mphil",
            "region": "HK",
            "campusType": "mainland",
            "school": "CUHK-Shenzhen",
            "schoolFull": "The Chinese University of Hong Kong, Shenzhen",
            "location": "Longgang, Shenzhen, Mainland China",
            "field": "CIE",
            "degree": "MPhil",
            "degreeGroup": "Master",
            "entry": "Fall 2027 / Spring",
            "deadline": "2027-05-31",
            "deadlineNote": "Same windows as PhD CIE",
            "opens": "2026-09-01",
            "funding": "partial",
            "fundingDetail": "Tuition RMB162k/yr from 2027; studentships/tuition support by merit",
            "gre": "Not required",
            "english": "TOEFL/IELTS as PhD",
            "requirements": ["Bachelor with ≥ Second Class honours typical"],
            "materials": ["pgapply.cuhk.edu.cn", "refs", "transcripts"],
            "notes": "Normative MPhil 24 months.",
            "applyUrl": "https://pgapply.cuhk.edu.cn/",
            "infoUrl": "https://sse-mphil-phd.cuhk.edu.cn/en/program/CIE",
            "detailLevel": "verified",
        },
        {
            "id": "hk-cuhksz-sds-phd",
            "region": "HK",
            "campusType": "mainland",
            "school": "CUHK-Shenzhen SDS",
            "schoolFull": "CUHK-Shenzhen School of Data Science",
            "location": "Shenzhen, Mainland China",
            "field": "Computer Science / Data Science",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "2027 cycle (rolling historically)",
            "deadline": "Check SDS page",
            "deadlineNote": "Prior cycle rolled to ~May; confirm 2027 on sds.cuhk.edu.cn",
            "opens": "Typically Sep",
            "funding": "full",
            "fundingDetail": "Tuition ~RMB140k (prior year); scholarships + TA duties for PhD",
            "gre": "Not required",
            "english": "University English rules",
            "requirements": ["Master or strong Bachelor", "Contact supervisor"],
            "materials": ["pgapply.cuhk.edu.cn", "RMB600"],
            "notes": "Separate from SSE CIE programme.",
            "applyUrl": "https://pgapply.cuhk.edu.cn/",
            "infoUrl": "https://sds.cuhk.edu.cn/en/phd-programmes-CSE/applications",
            "detailLevel": "portal-check",
        },
        {
            "id": "hk-cuhksz-msc-cie",
            "region": "HK",
            "campusType": "mainland",
            "school": "CUHK-Shenzhen",
            "schoolFull": "CUHK-Shenzhen SSE — MSc CIE",
            "location": "Shenzhen, Mainland China",
            "field": "CIE",
            "degree": "MSc",
            "degreeGroup": "Master",
            "entry": "Taught master's (2 yrs)",
            "deadline": "Batch schedule — prior year batches to May",
            "deadlineNote": "Check ssemsc.cuhk.edu.cn for 2027 batches",
            "opens": "Usually Sep prior year",
            "funding": "partial",
            "fundingDetail": "Tuition historically RMB288,000/2yrs; entrance scholarships up to full tuition",
            "gre": "Not required",
            "english": "Programme English rules",
            "requirements": ["Bachelor; AI/CS/engineering related preferred"],
            "materials": ["Online app", "RMB600 fee"],
            "notes": "Taught MSc — not research MPhil.",
            "applyUrl": "https://ssemsc.cuhk.edu.cn/en/node/98",
            "infoUrl": "https://ssemsc.cuhk.edu.cn/en/node/98",
            "detailLevel": "portal-check",
        },
        {
            "id": "hk-cityudg-msc-cs",
            "region": "HK",
            "campusType": "mainland",
            "school": "CityUHK (Dongguan)",
            "schoolFull": "City University of Hong Kong (Dongguan)",
            "location": "Songshan Lake, Dongguan, Mainland China",
            "field": "Computer Science",
            "degree": "MSc",
            "degreeGroup": "Master",
            "entry": "Fall (CityU HK degree certificate)",
            "deadline": "2026-07-31",
            "deadlineNote": "Listed for 2026 intake window; check PGA site for 2027 Fall update",
            "opens": "Open until deadline",
            "funding": "self",
            "fundingDetail": "Tuition RMB140,000/yr × 2 yrs; application fee free; deposit RMB30,000",
            "gre": "Not required",
            "english": "CET-6 425 / TOEFL 79 / IELTS 6.0 (or English-medium degree exemption)",
            "requirements": ["Recognized bachelor degree", "Recommendations"],
            "materials": ["PGA online application"],
            "notes": "Also MSc AI / MSc EEE. New campus; PhD pathways developing (3+1+N etc.).",
            "applyUrl": "https://pga.cityu-dg.edu.cn/en/computer-science",
            "infoUrl": "https://pga.cityu-dg.edu.cn/en/home",
            "detailLevel": "verified",
        },
        {
            "id": "hk-cityudg-msc-eee",
            "region": "HK",
            "campusType": "mainland",
            "school": "CityUHK (Dongguan)",
            "schoolFull": "City University of Hong Kong (Dongguan)",
            "location": "Dongguan, Mainland China",
            "field": "EEE",
            "degree": "MSc",
            "degreeGroup": "Master",
            "entry": "Fall",
            "deadline": "Check PGA site",
            "deadlineNote": "See Electrical & Electronic Engineering programme page",
            "opens": "Rolling toward deadline",
            "funding": "self",
            "fundingDetail": "Taught master's tuition — confirm on programme page",
            "gre": "Not required",
            "english": "Similar to MSc CS minima",
            "requirements": ["Bachelor in related field"],
            "materials": ["PGA application"],
            "notes": "Industrial/research schemes mentioned on admissions site.",
            "applyUrl": "https://pga.cityu-dg.edu.cn/en/home",
            "infoUrl": "https://www.cityu-dg.edu.cn/en/home",
            "detailLevel": "portal-check",
        },
        {
            "id": "hk-bnbu-cs-phd",
            "region": "HK",
            "campusType": "mainland",
            "school": "BNBU/UIC",
            "schoolFull": "Beijing Normal–Hong Kong Baptist University (UIC Zhuhai)",
            "location": "Zhuhai, Mainland China",
            "field": "Computer Science and Technology",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "Fall preferred",
            "deadline": "Rolling (year-round for CS)",
            "deadlineNote": "Sep 2026 intake deadline was 2026-07-31; after that → 2027 Spring/Fall",
            "opens": "Year-round for CS",
            "funding": "full",
            "fundingDetail": "Studentship RMB15,800/mo incl. tuition for PhD; tuition list RMB90,000/yr",
            "gre": "Not required",
            "english": "TOEFL 79 (or new 4.5 scale) / IELTS 6.5 / CET-6 500+B speaking",
            "requirements": ["Master or First-class Bachelor with research evidence"],
            "materials": ["BNBU GS application system"],
            "notes": "English-taught research degrees. Formerly UIC branding.",
            "applyUrl": "https://gs.bnbu.edu.cn/graduate1/Research_Postgraduate_Programme/Computer_Science_and_Technology.htm",
            "infoUrl": "https://gs.bnbu.edu.cn/admission/Application_Procedure/Research_Postgraduate_Programme.htm",
            "detailLevel": "verified",
        },
        {
            "id": "hk-bnbu-cs-mphil",
            "region": "HK",
            "campusType": "mainland",
            "school": "BNBU/UIC",
            "schoolFull": "Beijing Normal–Hong Kong Baptist University (UIC Zhuhai)",
            "location": "Zhuhai, Mainland China",
            "field": "Computer Science and Technology",
            "degree": "MPhil",
            "degreeGroup": "Master",
            "entry": "Fall (24 months)",
            "deadline": "Rolling",
            "deadlineNote": "Same CS year-round policy",
            "opens": "Year-round",
            "funding": "full",
            "fundingDetail": "Studentship RMB13,500/mo incl. tuition for MPhil",
            "gre": "Not required",
            "english": "Same as PhD language table",
            "requirements": ["Honours Bachelor typically First/Second class"],
            "materials": ["BNBU GS app"],
            "notes": "May transfer to PhD after assessment.",
            "applyUrl": "https://gs.bnbu.edu.cn/graduate1/Research_Postgraduate_Programme/Computer_Science_and_Technology.htm",
            "infoUrl": "https://gs.bnbu.edu.cn/",
            "detailLevel": "verified",
        },
    ]


def sg_programs():
    """Singapore CS/EE/AI related PhD and Master's programmes."""
    return [
        {
            "id": "sg-singa-phd",
            "region": "SG",
            "campusType": "main",
            "school": "SINGA",
            "schoolFull": "Singapore International Graduate Award (A*STAR + NUS/NTU/SUTD/SMU/SIT)",
            "location": "Singapore",
            "field": "Science & Engineering PhD",
            "degree": "PhD (SINGA)",
            "degreeGroup": "PhD",
            "entry": "August 2027 (also Jan 2028 for A*STAR/NTU)",
            "deadline": "2026-12-01",
            "deadlineNote": "23:59 GMT+8 for Aug 2027; Jan 2028 intake deadline 2027-06-01 (A*STAR & NTU only)",
            "opens": "Open until deadline",
            "funding": "full",
            "fundingDetail": "Full tuition; stipend ~S$2,700/mo rising to ~S$3,200 after QE; airfare up to S$1,500; settling-in S$1,000; typically no bond",
            "gre": "Not required by SINGA (host uni may have preferences)",
            "english": "TOEFL/IELTS if medium of instruction was not English",
            "requirements": [
                "Bachelor/Master in relevant science/engineering",
                "Apply via SINGA portal; choose supervisors/institutions",
                "Degree conferred by partner university",
            ],
            "materials": ["SINGA online app", "Transcripts", "2 refs", "English scores if needed", "Passport"],
            "notes": "Top route for international PhD in Singapore labs. Portal: sms-applicant-app.a-star.edu.sg",
            "applyUrl": "https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa",
            "infoUrl": "https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa",
            "detailLevel": "verified",
        },
        {
            "id": "sg-nus-cs-phd",
            "region": "SG",
            "campusType": "main",
            "school": "NUS",
            "schoolFull": "National University of Singapore — School of Computing",
            "location": "Singapore",
            "field": "CS / IS (PhD by Research)",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "August 2027 / January 2028",
            "deadline": "2026-12-15",
            "deadlineNote": "Aug intake cut-off 15 Dec; Jan intake cut-off 15 June (prior year). Apps accepted year-round for next intake.",
            "opens": "Now – 2026-12-15 (Aug 2027)",
            "funding": "full",
            "fundingDetail": "Competitive Research Scholarship: tuition + monthly stipend; +S$500/mo for 2 yrs after PhD QE. Renewable up to 4 years.",
            "gre": "GRE or GMAT typically required (codes GRE 0677 / TOEFL 9088)",
            "english": "TOEFL or IELTS",
            "requirements": [
                "Strong computing-related bachelor/master",
                "SoP + CV mandatory",
                "2 online referee reports",
                "Separate app+fee if applying to multiple departments",
            ],
            "materials": ["GDA System", "SoP", "CV", "Transcripts", "GRE/GMAT", "TOEFL/IELTS", "2 refs", "S$50 fee"],
            "notes": "Contact phd-info@comp.nus.edu.sg. Outcome ~3 months after deadline.",
            "applyUrl": "https://www.comp.nus.edu.sg/programmes/pg/phdcs/application/",
            "infoUrl": "https://www.comp.nus.edu.sg/programmes/pg/phdcs/scholarships/",
            "detailLevel": "verified",
        },
        {
            "id": "sg-nus-ece-phd",
            "region": "SG",
            "campusType": "main",
            "school": "NUS",
            "schoolFull": "National University of Singapore — ECE / CDE",
            "location": "Singapore",
            "field": "Electrical & Computer Engineering",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "August / January",
            "deadline": "2026-12-15",
            "deadlineNote": "Confirm ECE graduate portal; similar NUS research calendar to Computing",
            "opens": "Year-round toward intake cut-offs",
            "funding": "full",
            "fundingDetail": "NUS Research Scholarship / other awards competitive for full-time PhD",
            "gre": "Often required — check ECE admissions",
            "english": "TOEFL/IELTS",
            "requirements": ["Strong EE/CompE/related degree", "Research fit with ECE faculty"],
            "materials": ["NUS GDA", "SoP", "CV", "Transcripts", "Refs", "Tests"],
            "notes": "Apply via NUS Graduate Admission System to ECE programmes.",
            "applyUrl": "https://cde.nus.edu.sg/ece/graduate/phd/",
            "infoUrl": "https://cde.nus.edu.sg/ece/",
            "detailLevel": "portal-check",
        },
        {
            "id": "sg-nus-mcomp",
            "region": "SG",
            "campusType": "main",
            "school": "NUS",
            "schoolFull": "NUS Computing — Master of Computing",
            "location": "Singapore",
            "field": "MComp (Specialisations / General / AI)",
            "degree": "MComp / MComp AI",
            "degreeGroup": "Master",
            "entry": "August 2027",
            "deadline": "2027-01-31",
            "deadlineNote": "Application window 1 Oct 2026 – 31 Jan 2027",
            "opens": "2026-10-01",
            "funding": "self",
            "fundingDetail": "Taught master's — typically self-funded. MComp AI tuition previously ~S$61,600 excl. GST (~S$67k with GST). App fee ~S$109.",
            "gre": "Programme-dependent; check track",
            "english": "TOEFL/IELTS if required",
            "requirements": [
                "Good honours in computing, or related + IT experience (track-specific)",
                "MComp AI: solid computing & maths foundation",
            ],
            "materials": ["GDA System", "Transcripts", "CV", "Refs as required", "App fee"],
            "notes": "Tracks: Specialisations / General / AI. FT ~18 mo; PT available for some. Outcomes by May/June.",
            "applyUrl": "https://www.comp.nus.edu.sg/graduate/",
            "infoUrl": "https://www.comp.nus.edu.sg/programmes/pg/mcomp-ai/admissions/",
            "detailLevel": "verified",
        },
        {
            "id": "sg-nus-msc-dft",
            "region": "SG",
            "campusType": "main",
            "school": "NUS",
            "schoolFull": "NUS — MSc Digital Financial Technology",
            "location": "Singapore",
            "field": "Digital Financial Technology",
            "degree": "MSc",
            "degreeGroup": "Master",
            "entry": "August 2027",
            "deadline": "2027-01-31",
            "deadlineNote": "Same master's window as Computing (verify on programme page)",
            "opens": "2026-10-01",
            "funding": "self",
            "fundingDetail": "Coursework master's — self-funded; check fee schedule on NUS site",
            "gre": "Check programme page",
            "english": "TOEFL/IELTS if required",
            "requirements": ["Related bachelor; quantitative background preferred"],
            "materials": ["GDA application"],
            "notes": "Contact msc-dft@nus.edu.sg",
            "applyUrl": "https://www.comp.nus.edu.sg/graduate/",
            "infoUrl": "https://www.comp.nus.edu.sg/graduate/",
            "detailLevel": "portal-check",
        },
        {
            "id": "sg-ntu-ccds-phd",
            "region": "SG",
            "campusType": "main",
            "school": "NTU",
            "schoolFull": "Nanyang Technological University — College of Computing & Data Science",
            "location": "Singapore",
            "field": "Computing & Data Science",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "August 2027 / January 2028",
            "deadline": "2027-01-31",
            "deadlineNote": "University research default: Aug intake app open 1 Oct, close 31 Jan; Jan intake open 1 Jun close 31 Jul. Some schools earlier.",
            "opens": "2026-10-01 (Aug intake)",
            "funding": "full",
            "fundingDetail": "NTU Research Scholarship: tuition + stipend (from Jan 2026 scale often cited ~S$3,000 intl PhD / higher for Singaporeans — verify current)",
            "gre": "GRE often required; GATE ≥90th percentile may substitute for Indian applicants",
            "english": "TOEFL/IELTS (≤2 years old)",
            "requirements": [
                "Strong academic + research evidence",
                "≥1 academic referee",
                "Technical & English proficiency evidence",
            ],
            "materials": ["NTU Grad app", "SoP", "Transcripts", "GRE", "English", "Refs", "S$50 fee"],
            "notes": "Also MEng by research. CCDS PhD page: ntu.edu.sg CCDS.",
            "applyUrl": "https://www.ntu.edu.sg/admissions/graduate/radmissionguide",
            "infoUrl": "https://www.ntu.edu.sg/education/graduate-programme/ccds-phd-computing-datascience",
            "detailLevel": "verified",
        },
        {
            "id": "sg-ntu-eee-phd",
            "region": "SG",
            "campusType": "main",
            "school": "NTU",
            "schoolFull": "Nanyang Technological University — EEE",
            "location": "Singapore",
            "field": "Electrical & Electronic Engineering",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "August / January",
            "deadline": "2027-01-31",
            "deadlineNote": "Follow NTU research admission guide unless EEE posts special date",
            "opens": "2026-10-01",
            "funding": "full",
            "fundingDetail": "NTU Research Scholarship competitive for full-time PhD",
            "gre": "As per NTU research requirements",
            "english": "TOEFL/IELTS",
            "requirements": ["EE-related degree", "Research proposal/SoP"],
            "materials": ["NTU application portal"],
            "notes": "Strong for circuits, communications, power, robotics, etc.",
            "applyUrl": "https://www.ntu.edu.sg/eee/admissions/graduate-programmes",
            "infoUrl": "https://www.ntu.edu.sg/admissions/graduate/radmissionguide",
            "detailLevel": "portal-check",
        },
        {
            "id": "sg-ntu-msc-ai",
            "region": "SG",
            "campusType": "main",
            "school": "NTU",
            "schoolFull": "NTU CCDS — MSc Artificial Intelligence",
            "location": "Singapore",
            "field": "Artificial Intelligence",
            "degree": "MSc",
            "degreeGroup": "Master",
            "entry": "August 2027",
            "deadline": "2027-03-31",
            "deadlineNote": "Coursework Aug intake often closes 31 Mar; confirm CCDS portal when open",
            "opens": "Typically Nov–Mar window",
            "funding": "self",
            "fundingDetail": "Tuition S$63,220 (incl. GST, recent schedule). No general university scholarship for this coursework MSc. SC/SPR subsidies may apply.",
            "gre": "Check CCDS MSc admissions",
            "english": "TOEFL/IELTS if required",
            "requirements": ["Bachelor in related field", "App fee S$50", "Deposit S$5,000 on accept"],
            "materials": ["NTU coursework application"],
            "notes": "Also MSc Cyber Security / Data Science same fee band. ccdsmscprog@ntu.edu.sg",
            "applyUrl": "https://www.ntu.edu.sg/education/graduate-programme/master-of-science-in-artificial-intelligence",
            "infoUrl": "https://www.ntu.edu.sg/computing/admissions/graduate-programmes/master-of-science-programmes",
            "detailLevel": "verified",
        },
        {
            "id": "sg-ntu-msc-ds",
            "region": "SG",
            "campusType": "main",
            "school": "NTU",
            "schoolFull": "NTU CCDS — MSc Data Science / Cyber Security",
            "location": "Singapore",
            "field": "Data Science / Cyber Security",
            "degree": "MSc",
            "degreeGroup": "Master",
            "entry": "August 2027",
            "deadline": "2027-03-31",
            "deadlineNote": "Same coursework calendar family as MSAI",
            "opens": "Check NTU coursework guide",
            "funding": "self",
            "fundingDetail": "S$63,220 incl. GST (AY2025+ schedule); SC/SPR subsidies possible",
            "gre": "Programme-dependent",
            "english": "TOEFL/IELTS if required",
            "requirements": ["Related bachelor degree"],
            "materials": ["NTU Grad coursework app"],
            "notes": "Self-financed coursework master's.",
            "applyUrl": "https://www.ntu.edu.sg/admissions/graduate/cwadmissionguide",
            "infoUrl": "https://www.ntu.edu.sg/computing/admissions/graduate-programmes/master-of-science-programmes",
            "detailLevel": "portal-check",
        },
        {
            "id": "sg-smu-scis-phd",
            "region": "SG",
            "campusType": "main",
            "school": "SMU",
            "schoolFull": "Singapore Management University — School of Computing & Information Systems",
            "location": "Singapore",
            "field": "Computing & Information Systems",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "August 2027 (Term 1)",
            "deadline": "2027-01-31",
            "deadlineNote": "Open 1 Aug 2026 – 31 Jan 2027; Term 2 (Jan) closes 30 Jun prior year",
            "opens": "2026-08-01",
            "funding": "full",
            "fundingDetail": "SMU PhD scholarships typically cover tuition + stipend for full-time students (competitive)",
            "gre": "GRE/GMAT required unless bachelor/master from SMU/NUS/NTU/SUTD",
            "english": "TOEFL/IELTS if bachelor not English-taught",
            "requirements": [
                "Full-time only for standard PhD track",
                "Personal statement ≤600 words + research statement",
                "2 referee reports (academic preferred)",
                "App fee must be paid by deadline",
            ],
            "materials": ["SMU online app", "Transcripts", "Resume", "PS + RS", "GRE/GMAT", "English", "2 refs"],
            "notes": "Early applicants may get early offers. scis_phd@smu.edu.sg",
            "applyUrl": "https://computing.smu.edu.sg/phd/online-application",
            "infoUrl": "https://computing.smu.edu.sg/phd",
            "detailLevel": "verified",
        },
        {
            "id": "sg-smu-mitb",
            "region": "SG",
            "campusType": "main",
            "school": "SMU",
            "schoolFull": "SMU — Master of IT in Business / SCIS master's",
            "location": "Singapore",
            "field": "IT / Analytics / AI-related master's",
            "degree": "MITB / MSc tracks",
            "degreeGroup": "Master",
            "entry": "Multiple intakes — check programme",
            "deadline": "Programme-specific",
            "deadlineNote": "MITB and other SCIS master's have separate rounds — see computing.smu.edu.sg",
            "opens": "Rolling by programme",
            "funding": "self",
            "fundingDetail": "Professional master's — mostly self-funded; limited scholarships",
            "gre": "Programme-dependent",
            "english": "TOEFL/IELTS if required",
            "requirements": ["Bachelor + relevant background/experience"],
            "materials": ["SMU graduate application"],
            "notes": "Popular industry-oriented computing master's in Singapore.",
            "applyUrl": "https://computing.smu.edu.sg/master",
            "infoUrl": "https://computing.smu.edu.sg/master",
            "detailLevel": "portal-check",
        },
        {
            "id": "sg-sutd-phd",
            "region": "SG",
            "campusType": "main",
            "school": "SUTD",
            "schoolFull": "Singapore University of Technology and Design",
            "location": "Singapore",
            "field": "PhD (interdisciplinary / ASD/EPD/ESD/ISTD etc.)",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "January 2027 (also Sep intakes)",
            "deadline": "2026-09-30",
            "deadlineNote": "Jan 2027 PhD closes 30 Sep 2026; two intakes/year (Jan & Sep)",
            "opens": "Before Sep 2026 deadline",
            "funding": "full",
            "fundingDetail": "SUTD graduate scholarships: tuition and/or monthly stipend (competitive)",
            "gre": "Check SUTD PhD criteria",
            "english": "TOEFL/IELTS if required",
            "requirements": ["Strong STEM background", "Research fit with SUTD pillars"],
            "materials": ["SUTD online portal", "Transcripts", "Refs", "App fee ~S$21.80"],
            "notes": "Also EngD (SC/SPR only) and SUTD–NUS Joint PhD — same Jan 2027 deadline band.",
            "applyUrl": "https://www.sutd.edu.sg/admissions/graduate/phd/",
            "infoUrl": "https://www.sutd.edu.sg/admissions/graduate/phd/",
            "detailLevel": "verified",
        },
        {
            "id": "sg-sutd-meng",
            "region": "SG",
            "campusType": "main",
            "school": "SUTD",
            "schoolFull": "SUTD — Master of Engineering (Research)",
            "location": "Singapore",
            "field": "Engineering (Research)",
            "degree": "MEng",
            "degreeGroup": "Master",
            "entry": "January 2027",
            "deadline": "2026-09-30",
            "deadlineNote": "Open 16 Jul 2026 – 30 Sep 2026 for Jan 2027",
            "opens": "2026-07-16",
            "funding": "partial",
            "fundingDetail": "Research master's; scholarships possible but less guaranteed than PhD",
            "gre": "Check programme",
            "english": "TOEFL/IELTS if required",
            "requirements": ["Bachelor in related field"],
            "materials": ["SUTD portal", "S$21.80 fee"],
            "notes": "FT 12–18 months; PT 24–36 months.",
            "applyUrl": "https://www.sutd.edu.sg/programme-listing/master-of-engineering-research/application/",
            "infoUrl": "https://www.sutd.edu.sg/admissions/graduate/masters/",
            "detailLevel": "verified",
        },
        {
            "id": "sg-sutd-msc-ai",
            "region": "SG",
            "campusType": "main",
            "school": "SUTD",
            "schoolFull": "SUTD — MSc Technology & Design (Human-Centred AI etc.)",
            "location": "Singapore",
            "field": "AI / Design / Tech master's",
            "degree": "MSc",
            "degreeGroup": "Master",
            "entry": "January 2027 / Sep intakes by programme",
            "deadline": "2026-10-31",
            "deadlineNote": "Human-Centred AI for Venture Innovation: closes 31 Oct 2026 (Jan 2027). Other MSc tracks have Jun/Jul 2026 closings for Sep 2026 — check for next cycle.",
            "opens": "Programme-specific",
            "funding": "self",
            "fundingDetail": "Taught MSc — mostly self-funded; some SUTD scholarships/awards",
            "gre": "Usually not central",
            "english": "Programme English requirements",
            "requirements": ["Bachelor; interest in AI+design/venture tracks"],
            "materials": ["SUTD graduate application"],
            "notes": "Multiple MSc Tech & Design specialisations — verify each deadline.",
            "applyUrl": "https://www.sutd.edu.sg/admissions/graduate/masters/",
            "infoUrl": "https://www.sutd.edu.sg/admissions/graduate/masters/",
            "detailLevel": "verified",
        },
        {
            "id": "sg-sit-phd",
            "region": "SG",
            "campusType": "main",
            "school": "SIT",
            "schoolFull": "Singapore Institute of Technology",
            "location": "Singapore",
            "field": "Applied computing / engineering research",
            "degree": "PhD",
            "degreeGroup": "PhD",
            "entry": "Check SIT graduate calendar",
            "deadline": "Programme-specific",
            "deadlineNote": "SINGA partner; also own PhD pathways — check sit.edu.sg",
            "opens": "Check portal",
            "funding": "partial",
            "fundingDetail": "May combine SIT awards / SINGA / industry IPP",
            "gre": "Check programme",
            "english": "TOEFL/IELTS if required",
            "requirements": ["Relevant degree + research/industry fit"],
            "materials": ["SIT graduate application"],
            "notes": "Practice-oriented university; CS/engineering applied research growing.",
            "applyUrl": "https://www.singaporetech.edu.sg/graduate",
            "infoUrl": "https://www.singaporetech.edu.sg/graduate",
            "detailLevel": "portal-check",
        },
        {
            "id": "sg-sit-master",
            "region": "SG",
            "campusType": "main",
            "school": "SIT",
            "schoolFull": "Singapore Institute of Technology — Master's",
            "location": "Singapore",
            "field": "Computing / Engineering master's",
            "degree": "MSc / MEngTech",
            "degreeGroup": "Master",
            "entry": "Multiple — programme-specific",
            "deadline": "Programme-specific",
            "deadlineNote": "Each SIT master's has its own window",
            "opens": "Check programme pages",
            "funding": "self",
            "fundingDetail": "Mostly self-funded professional master's",
            "gre": "Usually not required",
            "english": "Programme requirements",
            "requirements": ["Bachelor + relevant experience for some tracks"],
            "materials": ["SIT application"],
            "notes": "Industry-aligned master's; verify 2027 intakes on SIT site.",
            "applyUrl": "https://www.singaporetech.edu.sg/graduate",
            "infoUrl": "https://www.singaporetech.edu.sg/graduate",
            "detailLevel": "portal-check",
        },
    ]


def meta():
    return {
        "title": "2027 港美新 CS/EE 硕博申请导航",
        "subtitle": "香港（含内地分校）· 美国约前100 · 新加坡主要院校 · PhD/硕士 · 教师名录与重点 AI 导师",
        "generated": "2026-09-13",
        "disclaimer": "截止日期与奖学金以各校官方申请系统为准；本站离线可打开分享。美国排名按 US News Grad CS 2026 大致档位，并用 Brown CS Open Rankings 扩充至约100所。老师信息含官方 Faculty Directory + 重点 AI/CS 导师主页（非全系穷尽名单）。",
        "hkpfs": {
            "stipend": "HK$344,400/年",
            "travel": "HK$14,400/年",
            "awards": 400,
            "rgcDeadline": "2026-12-01 12:00 HKT",
            "uniDeadline": "2026-12-01 23:59 HKT",
            "portal": "https://cerg1.ugc.edu.hk/hkpfs/index.html",
            "note": "仅适用于香港本校 PhD（UGC八校），不适用于内地分校。",
        },
        "singa": {
            "deadline": "2026-12-01 23:59 GMT+8",
            "intake": "August 2027",
            "portal": "https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa",
            "note": "新加坡国际博士奖学金；合作院校含 NUS/NTU/SUTD/SMU/SIT + A*STAR。",
        },
        "sources": [
            "RGC HKPFS call & FAQ",
            "HKU / CUHK / HKUST / CityU / PolyU official pages",
            "HKUST(GZ) FYTGS & Red Bird MPhil",
            "CUHK-Shenzhen SSE CIE & SDS",
            "CityUHK (Dongguan) PGA",
            "BNBU/UIC GS Computer Science",
            "NUS Computing PhD / MComp / graduate calendar",
            "NTU research & CCDS MSc admissions",
            "SMU SCIS PhD online application",
            "SUTD PhD / Masters admissions",
            "SINGA / A*STAR scholarship pages",
            "LEAP Alliance Fall 2027 CS PhD deadlines",
            "Stanford / MIT / Berkeley / CMU / UIUC official admissions",
            "Brown CS Open Rankings 2026 (US institutions)",
            "US News 2026 Best Computer Science Schools (band reference)",
        ],
    }


def main():
    programs = [attach_faculty(p) for p in (hk_programs() + sg_programs() + us_programs())]
    fac = faculty_payload()
    payload = {"meta": meta(), "programs": programs, "faculty": fac}
    out = Path(__file__).parent / "js" / "data.js"
    out.write_text(
        "window.ADMISSIONS_DATA = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )
    hk = sum(1 for p in programs if p["region"] == "HK")
    us = sum(1 for p in programs if p["region"] == "US")
    sg = sum(1 for p in programs if p["region"] == "SG")
    with_dir = sum(1 for p in programs if p.get("facultyDir"))
    print(
        f"Wrote {out} with {len(programs)} programs (HK={hk}, SG={sg}, US={us}); "
        f"facultyDirs={with_dir}; highlights={len(fac['highlights'])}"
    )


if __name__ == "__main__":
    main()
